server.port=24001

spring.datasource.url=jdbc:mysql://10.8.0.99:3306/gteam_vtdt_router?characterEncoding=UTF-8&dontTrackOpenResources=true
spring.datasource.username=gteam_dht
spring.datasource.password=Matkhau123!@!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

default.asset-version=1

config.client-asset-server-secret=a17a50
config.client-game-server-secret=ThisIsAKey123456
config.core-game-server-secret=ThisIsAKey123456